name: main

on:
   push:
      branches: [ ci ]

jobs:
   linters:
      runs-on: ubuntu-22.04

      strategy:
         matrix:
            node-version: [ 21.x ]

      steps:
         -  name: Checkout code
            uses: actions/checkout@v4

         -  name: Set up Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
               cache: 'yarn'
               node-version: ${{ matrix.node-version }}

         -  name: Install dependencies
            run: yarn

         -  name: Run lint
            run: yarn lint

   test:
      runs-on: ubuntu-22.04

      strategy:
         matrix:
            node-version: [ 21.x ]

      steps:
         -  name: Checkout code
            uses: actions/checkout@v4

         -  name: Set up Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
               cache: 'yarn'
               node-version: ${{ matrix.node-version }}

         -  name: Install dependencies
            run: yarn

         -  name: Run test
            run: yarn test

   build:
      runs-on: ubuntu-22.04

      strategy:
         matrix:
            node-version: [ 21.x ]

      needs: test

      steps:
         -  name: Checkout code
            uses: actions/checkout@v4

         -  name: Set up Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
               cache: 'yarn'
               node-version: ${{ matrix.node-version }}

         -  name: Install dependencies
            run: yarn

         -  name: Run build
            run: yarn build
